- name: setting up hostname
  hostname:
    name: "{{component}}"

- name: configuring erlang and rabbitmq repo
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/{{item}} | bash
  loop:
    - erlang/script.rpm.sh
    - rabbitmq-server/script.rpm.sh

- name: installing rabbitmq
  yum:
    name: "{{component}}-server"
    state: installed

- name: enable and restart {{component}} service
  service:
    name: "{{component}}-server"
    enabled: yes
    state: restarted

- name: creating {{component}} user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{rabbitmq_passwod}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present