- name: setting up hostname
  hostname:
    name: "{{component}}"

- name: Disable default MySQL module
  shell: yum module disable {{component}} -y

- name: creating repo {{component}} file
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/

- name: installing mysql server
  yum:
    name: mysql-community-server
    state: installed

- name: Enable and Restart "{{component}}" service
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Get temporary MySQL root password
  shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: mysql_temp_pass

- name: Set MySQL root password
  shell: >
    mysql --connect-expired-password -uroot -p'{{ mysql_temp_pass.stdout }}'
    -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';"