- name: setting up hostname
  hostname:
    name: "{{component}}"

- name: Disable default MySQL module
  shell: yum module disable {{component}} -y

- name: creating repo {{component}} file
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/

- name: installing mysql server
  yum:
    name: mysql-community-server
    state: installed

- name: Enable and Restart "{{component}}" service
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: setting up root password
  expect:
    command: mysql_secure_installation
    responses:
      'Enter password for user root:': ''
      'Set root password? [Y/n]': 'Y'
      'New password:': 'RoboShop@1'
      'Re-enter new password:': 'RoboShop@1'
      'Remove anonymous users? [Y/n]': 'Y'
      'Disallow root login remotely? [Y/n]': 'Y'
      'Remove test database and access to it? [Y/n]': 'Y'
      'Reload privilege tables now? [Y/n]': 'Y'


  