- name: Install maven
  yum:
    name: maven
    state: installed

- name: app_presetup
  import_tasks:
    file: app_presetup.yml

- name: install dependencies
  shell: mvn clean package; mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Load data
  import_tasks:
    file: mysql-client.yml

-  name: systemd_setup
   import_tasks:
    file: systemd_setup.yml

