- name: installing mysql-client
  yum:
    name: mysql
    state: installed

- name: Load the schema into MySQL
  shell: >
    mysql -h {{hostvars['mysql'].ansible_host}}
          -uroot
          -p{{mysql_password}}
          < /app/schema/{{component}}.sql