- name: installing mysql-client
  yum:
    name: mysql
    state: installed

- name: Load cities schema
  shell: |
    mysql -h {{hostvars['mysql'].ansible_host}} -uroot -p'{{ mysql_password }}' \
    -e "source {{app_path}}/schema/{{component}}.sql;"